function J18data = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  J18DATA = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a cell array.
%
%  J18DATA = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  J18data = importfile("C:\Users\ITSANIBONDIP\OneDrive - Tetra Pak\Documents\GitHub\psanibondi.github.io\jugger18\J18 - data.csv", [5, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Jul-2022 10:56:41

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2"];
opts.VariableTypes = ["double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName2", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName2", "EmptyFieldRule", "auto");

% Import the data
J18data = readtable(filename, opts);

%% Convert to output type
J18data = table2cell(J18data);
numIdx = cellfun(@(x) ~isnan(str2double(x)), J18data);
J18data(numIdx) = cellfun(@(x) {str2double(x)}, J18data(numIdx));
end